apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-ydmk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-ydmk
    app.kubernetes.io/part-of: test-app-qyzn
  name: test-component-ydmk
  namespace: build-e2e-hacbs-syuh
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component-ydmk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component-ydmk
    spec:
      containers:
      - image: quay.io/mkovarik/test-images@sha256:c081e6568ab9fada7b3b96899690167a791301879667024a013301979a401f60
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
