apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-ydmk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-ydmk
    app.kubernetes.io/part-of: test-app-qyzn
  name: test-component-ydmk
  namespace: build-e2e-hacbs-syuh
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: test-component-ydmk
status:
  loadBalancer: {}
